<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.service.proto

namespace User;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>user.UserLockRequest</code>
 */
class UserLockRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 userId = 1;</code>
     */
    protected $userId = 0;
    /**
     * Generated from protobuf field <code>int64 day = 2;</code>
     */
    protected $day = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $userId
     *     @type int|string $day
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\UserService::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 userId = 1;</code>
     * @return int|string
     */
    public function getUserId()
    {
        return $this->userId;
    }

    /**
     * Generated from protobuf field <code>int64 userId = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkInt64($var);
        $this->userId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 day = 2;</code>
     * @return int|string
     */
    public function getDay()
    {
        return $this->day;
    }

    /**
     * Generated from protobuf field <code>int64 day = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setDay($var)
    {
        GPBUtil::checkInt64($var);
        $this->day = $var;

        return $this;
    }

}

