<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.service.proto

namespace User;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * User 服务的各个接口的请求/响应结构
 *
 * Generated from protobuf message <code>user.UserOnlineRequest</code>
 */
class UserOnlineRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string token = 1;</code>
     */
    protected $token = '';
    /**
     * Generated from protobuf field <code>string LastInnerIp = 2;</code>
     */
    protected $LastInnerIp = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $token
     *     @type string $LastInnerIp
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\UserService::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string token = 1;</code>
     * @return string
     */
    public function getToken()
    {
        return $this->token;
    }

    /**
     * Generated from protobuf field <code>string token = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->token = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string LastInnerIp = 2;</code>
     * @return string
     */
    public function getLastInnerIp()
    {
        return $this->LastInnerIp;
    }

    /**
     * Generated from protobuf field <code>string LastInnerIp = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setLastInnerIp($var)
    {
        GPBUtil::checkString($var, True);
        $this->LastInnerIp = $var;

        return $this;
    }

}

