<?php


namespace Annotation\Rpc;


use Annotation\Attribute;
use JetBrains\PhpStorm\Pure;


/**
 * Class Producer
 * @package Annotation\Rpc
 */
#[\Attribute(\Attribute::TARGET_CLASS)] class Producer extends Attribute
{


	/**
	 * Producer constructor.
	 * @param string $name
	 */
	public function __construct(private string $name)
	{
	}


	/**
	 * @param array $handler
	 * @return mixed
	 */
	#[Pure] public function execute(array $handler): mixed
	{
		return parent::execute($handler); // TODO: Change the autogenerated stub
	}

}
