<?php


namespace Annotation;


/**
 * Class Aspect
 * @package Annotation
 */
#[\Attribute(\Attribute::TARGET_METHOD | \Attribute::TARGET_FUNCTION)] class Aspect extends Attribute
{


    /**
     * Aspect constructor.
     */
    public function __construct()
    {
    }


    /**
     * @param array $handler
     * @return mixed
     */
    public function execute(array $handler): mixed
    {
        return parent::execute($handler); // TODO: Change the autogenerated stub
    }


}
