<?php


namespace Annotation;


/**
 * Class Kafka
 * @package Annotation
 */
#[\Attribute(\Attribute::TARGET_CLASS)] class Kafka extends Attribute
{


    /**
     * Kafka constructor.
     * @param string $topic
     */
    public function __construct(public string $topic, public string $groupId)
    {

    }


    /**
     * @param array $handler
     * @return mixed
     */
    public function execute(array $handler): mixed
    {
        return parent::execute($handler); // TODO: Change the autogenerated stub
    }


}
