<?php


namespace Annotation;


#[\Attribute(\Attribute::TARGET_METHOD)] class Port extends Attribute
{


	/**
	 * Port constructor.
	 * @param int $port
	 */
	public function __construct(public int $port)
	{
	}


	/**
	 * @param array $handler
	 * @return mixed
	 */
	public function execute(array $handler): mixed
	{
		return parent::execute($handler); // TODO: Change the autogenerated stub
	}

}
